A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('start_here.urls')),
    path('', include('quizzes.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('feedback.urls')),
    path('', include('maps.urls')),
]
# print('!'*111)
handler404 = 'home.views.not_found'

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('details/<int:tut_id>/<tut_slug>/', views.DetailView.as_view(), name='details'),
    path('delete/<int:tut_id>/', views.DeleteView.as_view(), name='delete'),
    path('update/<int:tut_id>/', views.UpdateView.as_view(), name='update'),
    path('create/<page_no>/', views.CreateView.as_view(), name='create'),
    path('reply/<int:tut_id>/<int:comment_id>/', views.TutorialAddReplyView.as_view(), name='add_reply'),
    path('search/', views.TutorialSearchView.as_view(), name='search'),
    path('articles/<int:art_id>/<str:slog>/', views.MongardArt),
    path('articles/<str:slog>/', views.roocketArt),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField


class Tutorial(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='tuts')
    title = models.CharField(max_length=167)
    body = RichTextField()
    slug = models.SlugField(null=True, allow_unicode=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    score = models.IntegerField(default=0)
    img = models.ImageField(upload_to='static/media/%Y/%m/', blank=True)
    imgurl = models.CharField(max_length=311, blank=True)

    class Meta:
        ordering = ('-score',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('home:details', args=(self.id, self.slug))

    def comments_count(self):
        return self.tcomments.count()


class Comment(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE, related_name='ucommens')
    tut = models.ForeignKey(Tutorial, on_delete=models.CASCADE, related_name='tcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)
    approve = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

home/forms.py
from django import forms
from .models import Tutorial, Comment
from ckeditor.widgets import CKEditorWidget


class TutorialCreateForm(forms.ModelForm):
    class Meta:
        model = Tutorial
        # fields = ['title', 'body', 'created']
        fields = '__all__'


class TutorialUpdateForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Tutorial
        fields = '__all__'


class TutorialSearchForm(forms.Form):
    search = forms.CharField()


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {'body': 'تلاش میکنم سوالات شما را در کمتر از یک روز پاسخ بدم'}
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 6})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {'body': 'پاسخ شما به این نظر'}
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'rows': 6})
        }

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Tutorial, Comment
from .forms import TutorialCreateForm, TutorialUpdateForm, CommentCreateForm, CommentReplyForm, TutorialSearchForm
from django.contrib import messages
from django.views import View
from django.utils.text import slugify
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import requests
from bs4 import BeautifulSoup


class HomeView(View):
    form_class = TutorialSearchForm

    def get(self, request):
        allT, oneT = None, None
        try:
            allT = Tutorial.objects.order_by('-created')[:9]
            # print(str(allT.query))
            oneT = allT[0]
        except Exception as ex:
            messages.error(request, ex, 'warning')
        return render(request, 'home/index.html', {'allT': allT, 'oneT': oneT, 'form': self.form_class})

class TutorialSearchView(View):
    def get(self, request):
        tuts = Tutorial.objects.filter(body__icontains=request.GET['q'])
        return render(request, 'home/search.html', {'tuts': tuts})

class DetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.tut = get_object_or_404(Tutorial, pk=kwargs['tut_id'])
        self.comments = self.tut.tcomments.filter(is_reply=False, approve=True)
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, 'home/detail.html',
                      {'tut': self.tut, 'comments': self.comments,
                       'form': self.form_class, 'reply_form': self.form_class_reply})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.tut = self.tut
            new_comment.save()
            messages.success(request, 'نظر شما با موفقیت ثبت شد. بعد از تایید، نمایش داده خواهد شد', 'success')
            return redirect('home:details', self.tut.id, self.tut.slug)
        return render(request, 'home/detail.html', {'tut': self.tut, 'comments': self.comments, 'form': form})


class DeleteView(LoginRequiredMixin, View):
    def get(self, req, tut_id):
        Tutorial.objects.get(id=tut_id).delete()
        messages.warning(req, 'این مورد آموزشی با موافقیت حذف گردید', 'warning')
        return redirect('home:home')


class CreateView(LoginRequiredMixin, View):
    form_class = TutorialCreateForm
    temp_name = 'home/create.html'

    def get(self, request, page_no):
        res = {}
        # try:
        #     session = requests.Session()
        #     # r = session.get('https://realpython.com/tutorials/basics/')
        #     # r = session.get(f'https://www.mongard.ir/articles/?page={page_no}')
        #     r = session.get('https://roocket.ir/articles?category=python')
        #     content = BeautifulSoup(r.text, 'html.parser')
        #     # res = content.find( id = "the-best-way-to-get-started" )
        #     # res = content.find_all('h2', class_="card-title")
        #     # res = content('h2')
        #     res = content.find_all('h4', class_="mt-3 mb-4")
        # except Exception as N:
        #     res = N
        form = self.form_class
        return render(request, self.temp_name, {'form': form, 'res': res})

    def post(self, request, page_no):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            new_tut = form.save(commit=False)
            new_tut.slug = slugify(form.cleaned_data['title'][:30], allow_unicode=True)
            new_tut.save()
            messages.success(request, 'یک مورد آموزشی جدید ایجاد گردید', 'success')
            return redirect('home:home')
        return render(request, self.temp_name, {'form': form})


class UpdateView(LoginRequiredMixin, View):
    form_class = TutorialUpdateForm
    temp_name = 'home/update.html'
    
    def setup(self, request, *args, **kwargs):
        self.tut = Tutorial.objects.get(pk=kwargs['tut_id'])
        super().setup(request, *args, **kwargs)

    def get(self, request, tut_id):
        form = self.form_class(instance=self.tut)
        return render(request, self.temp_name, {'form': form})

    def post(self, request, tut_id):
        form = self.form_class(request.POST, request.FILES, instance=self.tut)
        if form.is_valid():
            new_tut = form.save(commit=False)
            new_tut.slug = slugify(form.cleaned_data['title'][:30], allow_unicode=True)
            new_tut.save()
            messages.success(request, 'اصلاحات باموافقیت ثبت گردید', 'success')
            return redirect('home:details', self.tut.id, self.tut.slug)
        return render(request, self.temp_name, {'form': form})


class TutorialAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, tut_id, comment_id):
        tut = get_object_or_404(Tutorial, pk=tut_id)
        comment = get_object_or_404(Comment, pk=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.tut = tut
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'پاسخ شما با موفقیت ثبت شد. بعد از تایید، نمایش داده خواهد شد', 'success')
        return redirect('home:details', tut.id, tut.slug)


def MongardArt(req, art_id, slog):
    try:
        session = requests.Session()
        r = session.get(f'https://www.mongard.ir/articles/{art_id}/{slog}/')
        content = BeautifulSoup(r.text, 'html.parser')
        res = content('main')
    except Exception as N:
        res = N
    return render(req, 'home/MongardArt.html', {'res': res})


def roocketArt(req, slog):
    try:
        session = requests.Session()
        r = session.get(f'https://roocket.ir/articles/{slog}/')
        content = BeautifulSoup(r.text, 'html.parser')
        res = content.find_all('article', class_='content-area')
    except Exception as N:
        res = N
    return render(req, 'home/roocketArt.html', {'res': res})


def not_found(request, exception):
    return render(request, '404.html')

home/templates/home/MongardArt.html
{% extends 'base.html' %}

{% block b1 %}
    <style>pre{text-align: left;}</style>
    {{ res|safe }}
    <hr>
    <textarea name="" id="" cols="100" rows="20">
        {{ res|safe }}
    </textarea>
{% endblock %}

home/templates/home/create.html
{% extends 'base.html' %}

{% block b1 %}
    <style>
        #id_title, #id_body, #id_imgurl {
            width: 90%
        }
    </style>
    <form action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="ایجاد">
    </form>
    {{ res|safe }}
<!--    {{ res|safe }}-->
<!--    {% for r in res %}-->
<!--        {% for t in r %}-->
<!--            {{t|safe}}-->
<!--        {% endfor %}-->
<!--    {% endfor %}-->
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block b1 %}
    <script>function sss(d){$(d).next().slideToggle()}</script>
    <style>
        pre{text-align: left;direction:ltr}
        article.content-area {background-color: rgba(14,35,56) !important; padding:11px}
    </style>
    <div style="text-align:right">
        <h1 class="fa-3x">{{ tut.title }}</h1>

        <p>
            <img src="{{ tut.imgurl }}" style="width: 100%;border-radius: 1.75rem" >
        </p>
        <small>{{ tut.created }}</small><br>
        {% if request.user.is_superuser %}
            <a href="{% url 'home:delete' tut.id %}" class="btn btn-warning"> حذف </a>
            <a href="{% url 'home:update' tut.id %}" class="btn btn-info"> اصلاح </a>
        {% endif %}
        <hr>
        <p>{{ tut.body|safe }}</p>
        <p>امتیاز : {{ tut.score }}</p>
        <h4>ارسال نظر</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="ارسال" class="btn btn-success col-md-2">
        </form>
        <hr>
        <p>تاحالا  {{ tut.comments_count }} نفر نظر دادند</p>
        {% for c in comments %}
            <div class="card bg-dark">
                <p class="card-header" style="color:gray">
                    {{ c.user.first_name }} {{ c.user.last_name }} | {{ c.created |timesince }}
                </p>
                <p class="card-body">{{ c.body }}</p>
                <p class="btn btn-info col-md-1" onclick="sss(this)" style="position:absolute;left:4px;top:4px">پاسخ</p>
                <div class="mr-3 ml-3" style="display:none">
                    <form action="{% url 'home:add_reply' tut.id c.id %}" method="post">
                        {% csrf_token %}
                        {{ reply_form.as_p }}
                        <input type="submit" value=" ارسال " class="btn btn-success">
                    </form><br>
                </div>

                {% with replies=c.rcomments.all %}
                    {% for r in replies %}
                        {% if r.approve %}
                        <div class="bg-primary p-2 mb-2 mr-5 ml-2">
                            {{ r.user }} <br> {{ r.body }}
                        </div>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </div><br>
        {% empty %}
            <p></p>
        {% endfor %}
    </div>
{% endblock %}

home/templates/home/roocketArt.html
{% extends 'base.html' %}

{% block b1 %}
    <style>
        pre{text-align: left;direction:ltr}
        article.content-area {background-color: rgba(14,35,56) !important; padding:11px}
    </style>
    {{ res|safe }}
    <hr>
    <textarea name="" id="" cols="100" rows="20">
        {{ res|safe }}
    </textarea>
{% endblock %}

home/templates/home/search.html
{% extends 'base.html' %}

{% block b1 %}
{% for t in tuts %}
<div class="card bg-dark text-info mb-3">{{ forloop.counter }}
    <div class="row g-0">
        <div class="col-md-4">
            <a href="{{ t.get_absolute_url }}">
                <img src="{{ t.imgurl }}" class="img-fluid rounded-start" alt="...">
            </a>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{ t.title }}</h5>
                <p class="card-text text-muted">{{ t.body|striptags |truncatewords:25 }}</p>
                <div class="row">
                    <div class="col-md-10"><small class="text-muted">{{ t.created |timesince }}</small></div>
                    <div class="col-md-2"><small class="text-muted">امتیاز {{ t.score }}</small></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}

{% block b1 %}
    <style>
        #id_title, #id_body, #id_imgurl {
            width: 90%
        }
    </style>
    <form action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ثبت">
    </form>
{% endblock %}