A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('start_here.urls')),
    path('', include('quizzes.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('feedback.urls')),
    path('', include('maps.urls')),
]
# print('!'*111)
handler404 = 'home.views.not_found'

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/',    views.UserLoginView.as_view(),    name='user_login'),
    path('logout/',   views.UserLogoutView.as_view(),   name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('password/reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField(default=0)
    bio = models.TextField(null=True, blank=True)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile


class UserRegistrationForm(forms.Form):
    username = forms.CharField(label='نام کاربری', widget=forms.TextInput(attrs={'class': 'form-control', 'dir': 'ltr'}), label_suffix=' *')
    email = forms.EmailField(label='ایمیل', widget=forms.EmailInput(attrs={'class': 'form-control', 'dir': 'ltr'}), label_suffix=' *')
    password = forms.CharField(label='کلمه عبور', widget=forms.PasswordInput(attrs={'class': 'form-control'}), label_suffix=' *')
    first_name = forms.CharField(required=False, label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'نام (اختیاری)'}))
    last_name = forms.CharField(required=False, label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'فامیلی (اختیاری)'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('ایمیل تکراری است')
        return email
    
    def clean(self):
        cd = super().clean()
        fn = cd.get('first_name')
        ln = cd.get('last_name')
        if 'hasan' in fn:
            raise ValidationError('با حسن قهرم')


class UserLoginForm(forms.Form):
    username = forms.CharField(label='نام کاربری یا ایمیل', widget=forms.TextInput(attrs={'class': 'form-control', 'dir': 'ltr'}), label_suffix=' *')
    password = forms.CharField(label='کلمه عبور', widget=forms.PasswordInput(attrs={'class': 'form-control'}), label_suffix=' *')


COLORS = (
    ("red", "قرمز"),
    ("2", "Two"),
    ("3", "Three"),
    ("4", "Four"),
    ("5", "Five"),
)


class EditUserForm(forms.ModelForm):
    email = forms.EmailField(label='ایمیل')
    fn = forms.CharField(label='نام')
    ln = forms.CharField(label='فامیلی')
    # bg = forms.ChoiceField(choices=COLORS)
    bg = forms.CharField()
    fg = forms.CharField()

    class Meta:
        model = Profile
        fields = ('age', 'bio')
        labels = {'age': 'سن', 'bio': 'بیوگرافی'}
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': 2})
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm, EditUserForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from start_here.my_settings import MySetting


class UserRegisterView(View):
    form_class = UserRegistrationForm
    temp_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.temp_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                u = User.objects.create_user(cd['username'], cd['email'], cd['password'])
                u.first_name = cd['first_name']
                u.last_name = cd['last_name']
                u.save()
                messages.success(request, 'حساب کاربری شما ایجاد گردید. لطفا للاگین کنید', 'success')
            except Exception as ex:
                messages.error(request, 'با این نام کاربری قبلا ثبت نام شده است', 'danger')
                return redirect('accounts:user_register')
            return redirect('accounts:user_login')
        return render(request, self.temp_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    temp_name = 'accounts/login.html'
    
    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.temp_name, {'form': form, 'bg': 'background:red'})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            u = authenticate(request, username=cd['username'], password=cd['password'])
            if u is not None:
                login(request, u)
                messages.success(request, 'خوش آمدید', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            else:
                messages.error(request, 'نام کاربری یا کلمه عبور نادرسته', 'danger')
        return render(request, self.temp_name, {'form': form, 'bg': 'background:red'})


class UserLogoutView(LoginRequiredMixin, View):
    # login_url = '/kkk/ff/'
    def get(self, request):
        logout(request)
        messages.success(request, 'به امید دیدار', 'success')
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    form_class = EditUserForm

    def get(self, request, user_id):
        is_following = False
        tuts = request.user.tuts.all()
        m = MySetting(request)
        form = self.form_class(
            instance=request.user.profile,
            initial={'email': request.user.email, 'fn': request.user.first_name, 'ln': request.user.last_name,
                     'bg': m.setting.get('bgc'), 'fg': m.setting.get('frc')})
        # relation = Relation.objects.filter(from_user=request.user, to_user=user)
        # if relation.exists():
        #     is_following = True
        return render(request, 'accounts/profile.html',
                      {'tuts': tuts, 'is_following': is_following, 'form': form})

    def post(self, request, user_id):
        form = self.form_class(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data['email']
            request.user.first_name = form.cleaned_data['fn']
            request.user.last_name = form.cleaned_data['ln']
            request.user.save()
            m = MySetting(request)
            m.avazkon(form.cleaned_data['bg'], form.cleaned_data['fg'])
            messages.success(request, 'پروفایل با موفقیت ذخیره شد', 'success')
        return redirect('accounts:user_profile', request.user.id)


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block b1 %}
<div class="login mb-4 mx-auto col-md-5">
    <form action="" method="post" class="border rounded p-3">
        {% csrf_token %}
        {{ form.as_p }}
        <p class="small mt-n2 text-right"><a href="{% url 'accounts:reset_password' %}">فراموشی رمز عبور ؟</a></p>
        <input type="submit" value="ورود" class="btn btn-success btn-lg px-4 mt-2 w-100">
    </form>
    <div class="d-flex text-muted small w-100 mx-auto mt-4">
        <span class="flex-fill border-top" style="margin-top:1.1rem;"></span>
        <p class="my-1 px-2">ثبت نام</p>
        <span class="flex-fill border-top" style="margin-top:1.1rem;"></span>
    </div>
    <a href="{% url 'accounts:user_register' %}" class="btn btn-secondary border w-100">ایجاد حساب کاربری جدید</a>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block b1 %}
  <h3>کلمه عبور شما با موفقیت عوض شد</h3>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block b1 %}
    {% if validlink %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="تغییر">
    </form>
    {% else %}
        <h2>این لینک معتبر نیست. دوباره سعی کنید</h2>
    {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block b1 %}
  <h3>یک ایمیل برای شما ارسال شد.</h3>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
<h3>شخصی برای ایمیل {{ email }} درخواست بازنشانی رمز عبور کرده است.</h3>
<h4>در صورتی که شما بوده اید از لینک زیر استفاده کنید:</h4>
<hr>
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block b1 %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ارسال">
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block b1 %}
    <h6 class="text-center">{{ request.user.first_name }} {{ request.user.last_name }}</h6>
    <div dir="ltr">id: {{ request.user.id }}   username: {{ request.user }}</div>
    <form action="" method="post" class="border rounded p-3 mb-4 col-md-12">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ذخیره" class="btn btn-success col-md-2">
    </form>
zz {{mys.bgc}}
    <div class="card bg-dark">
        {% for t in tuts %}
            <a href="{{ t.get_absolute_url }}" class="card-body">{{ t.title }}</a>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block b1 %}
<div class="signup mx-auto col-md-5">
    <form action="" method="post" class="border rounded p-3">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ایجاد حساب کاربری" class="btn btn-success btn-lg px-4 mt-2 w-100">
    </form>
    <div class="text-right text-muted small">
        <p> حساب کاربری دارم <a href="{% url 'accounts:user_login' %}"> ورود </a></p>
    </div>
</div>

{% endblock %}