A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('start_here.urls')),
    path('', include('quizzes.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('feedback.urls')),
    path('', include('maps.urls')),
]
# print('!'*111)
handler404 = 'home.views.not_found'

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/',    views.UserLoginView.as_view(),    name='user_login'),
    path('logout/',   views.UserLogoutView.as_view(),   name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('password/reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('details/<int:tut_id>/<tut_slug>/', views.DetailView.as_view(), name='details'),
    path('delete/<int:tut_id>/', views.DeleteView.as_view(), name='delete'),
    path('update/<int:tut_id>/', views.UpdateView.as_view(), name='update'),
    path('create/<page_no>/', views.CreateView.as_view(), name='create'),
    path('reply/<int:tut_id>/<int:comment_id>/', views.TutorialAddReplyView.as_view(), name='add_reply'),
    path('search/', views.TutorialSearchView.as_view(), name='search'),
    path('articles/<int:art_id>/<str:slog>/', views.MongardArt),
    path('articles/<str:slog>/', views.roocketArt),
]

templates/inc/foo.html
<footer>
    <div class="fAnimatePlayContainer">
        <div class="FooterAnimateContainer">
            <div class="FooterAnimateGrid">
                <div class="FooterAnimateFade"></div>
                <div class="FooterAnimateLines"></div>
                <div class="FooterBackgroundContainer"></div>
            </div>
        </div>
    </div>
</footer>

templates/inc/foo2.html
<footer>
    <div id="light">
        <div id="lineh1"></div>
        <div id="lineh2"></div>
        <div id="lineh3"></div>
        <div id="lineh4"></div>
        <div id="lineh5"></div>
        <div id="lineh6"></div>
        <div id="lineh7"></div>
        <div id="lineh8"></div>
        <div id="lineh9"></div>
        <div id="lineh10"></div>
        <div id="lineh11"></div>
        <div id="lineh12"></div>
    </div>
</footer>
<style>
		#light{
			position: relative;
			top: -455px;
		}
		#lineh1{
			position: absolute;
			left: 0;
			height: 10px;
			background: #5500AA;
			animation: lineH 4s 5s infinite linear;
		}
		#lineh2{
			position: absolute;
			left: 0;
			top: 40px;
			height: 10px;
			background: #AA2B00;
			animation: lineH 5s 0.5s infinite linear;
		}
		#lineh3{
			position: absolute;
			left: 0;
			top: 70px;
			height: 10px;
			background: #00D4FF;
			animation: lineH 5s 2s infinite linear;
		}
		#lineh4{
			position: absolute;
			right: 0;
			top: 100px;
			height: 10px;
			background: #00AA2B;
			animation: lineH 5s 1s infinite linear;
		}
		#lineh5{
			position: absolute;
			left: 0;
			top: 130px;
			height: 10px;
			background: #AA8000;
			animation: lineH 5s 4s infinite linear;
		}
		#lineh6{
			position: absolute;
			right: 0;
			top: 160px;
			height: 10px;
			background: #AAFF00;
			animation: lineH 4s 1s infinite linear;
		}
		#lineh7{
			position: absolute;
			right: 0;
			top: 190px;
			height: 10px;
			background: #D50055;
			animation: lineH 4s 0s infinite linear;
		}
		#lineh8{
			position: absolute;
			left: 0;
			top: 220px;
			height: 10px;
			background: #00FFFF;
			animation: lineH 4s 1.5s infinite linear;
		}
		#lineh9{
			position: absolute;
			left: 0;
			top: 250px;
			height: 10px;
			background: #2B002B;
			animation: lineH 5s 2s infinite linear;
		}
		#lineh10{
			position: absolute;
			right: 0;
			top: 280px;
			height: 10px;
			background: #005580;
			animation: lineH 4s 3s infinite linear;
		}
		#lineh11{
			position: absolute;
			right: 0;
			top: 310px;
			height: 10px;
			background: #FF557F;
			animation: lineH 4s 1s infinite linear;
		}
		#lineh12{
			position: absolute;
			right: 0;
			top: 340px;
			height: 10px;
			background: #85B085;
			animation: lineH 6s 1s infinite linear;
		}
		@keyframes lineH{
			0%{
				width: 0%;
			}
			100%{
        width: 95%;opacity: 0;
      }
    }

</style>

templates/inc/footer.html
<footer class="footer ">
    <div class="container">
        <div class="mx-auto mt-4 mb-0" style="max-width: 768px;">
            <div style="display:block;position:relative;">
                <div style="display:block;width:100%;padding-top:12.5%;"></div>
                <div class="rpad rounded border" data-unit="8x1"
                     style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;"></div>
            </div>
            <a class="small text-muted" href="/account/join/" rel="nofollow"><i class="fa fa-info-circle mr-1"
                                                                                aria-hidden="true"></i>Remove ads</a>
        </div>

        <p class="text-center text-muted w-75 mx-auto">
            © 2012–2023 Real&nbsp;Python&nbsp;⋅
            <a href="/newsletter/">Newsletter</a>&nbsp;⋅
            <a href="/podcasts/rpp/">Podcast</a>&nbsp;⋅
            <a href="https://www.youtube.com/realpython">YouTube</a>&nbsp;⋅
            <a href="https://twitter.com/realpython">Twitter</a>&nbsp;⋅
            <a href="https://facebook.com/LearnRealPython">Facebook</a>&nbsp;⋅
            <a href="https://www.instagram.com/realpython/">Instagram</a>&nbsp;⋅
            <a href="/">Python&nbsp;Tutorials</a>&nbsp;⋅
            <a href="/search">Search</a>&nbsp;⋅
            <a href="/privacy-policy/">Privacy Policy</a>&nbsp;⋅
            <a href="/energy-policy/">Energy Policy</a>&nbsp;⋅
            <a href="/sponsorships/">Advertise</a>&nbsp;⋅
            <a href="/contact/">Contact</a><br>❤️ Happy Pythoning!
        </p>
    </div>
</footer>

templates/inc/navbar0.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column" style="background-color: rgb(14,151,195);">
  <div class="container flex-row">

    <a class="navbar-brand" href="{% url 'home:home' %}" style="padding:2px">
      <img src="/static/media/w1.jfif" height="70" class="d-inline-block align-top" alt="اموزش پایتون">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">
        {% include 'inc/menu.html' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'start_here' %}"
             style="color:black;border: 1px solid skyblue;border-radius: 11px;"> شروع </a>
        </li>
      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/search" title="Search"><span class="d-block d-lg-none"><i class="fa fa-search" aria-hidden="true"></i> Search</span><span class="d-none d-lg-block"><i class="fa fa-search" aria-hidden="true"></i></span></a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search"><i class="fa fa-search fa-fw text-muted pl-2" aria-hidden="true"></i></a>
          <input class="search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q" autocomplete="off">
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">
          {% if request.user.is_superuser %}
              <li class="nav-item form-inline">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'home:create' 1 %}">ایجاد</a>
              </li>
          {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> خروج </a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_register' %}"
                   style="color:white;border-radius: 11px;"> ثبت نام </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> ورود </a>
              </li>
          {% endif %}

      </ul>


    </div>

  </div>



</nav>

templates/inc/navbar1.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column" style="">
  <div class="container flex-row">

    <a class="navbar-brand" href="{% url 'home:home' %}" style="padding:2px">
      <img src="http://127.0.0.1:8000//static/media/t.gif" height="70" class="d-inline-block align-top" alt="اموزش پایتون">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">
        {% include 'inc/menu.html' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'start_here' %}" style="color:black"> شروع </a>
        </li>
      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/search" title="Search"><span class="d-block d-lg-none"><i class="fa fa-search" aria-hidden="true"></i> Search</span><span class="d-none d-lg-block"><i class="fa fa-search" aria-hidden="true"></i></span></a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search"><i class="fa fa-search fa-fw text-muted pl-2" aria-hidden="true"></i></a>
          <input class="search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q" autocomplete="off">
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">
          {% if request.user.is_superuser %}
              <li class="nav-item form-inline">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'home:create' 1 %}">ایجاد</a>
              </li>
          {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="btn" href="{% url 'accounts:user_logout' %}"> خروج </a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'accounts:user_register' %}"> ثبت نام </a>
              </li>
              <li class="nav-item">
                <a class="btn" href="{% url 'accounts:user_login' %}"> ورود </a>
              </li>
          {% endif %}

      </ul>


    </div>

  </div>



</nav>

templates/inc/navbar2.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column" style="background-color: peru;">
  <div class="container flex-row">

    <a class="navbar-brand" href="{% url 'home:home' %}" style="padding:2px">
      <img src="/static/media/w2.png" height="70" class="d-inline-block align-top" alt="اموزش پایتون">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">
        {% include 'inc/menu.html' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'start_here' %}"> شروع </a>
        </li>
      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/search" title="Search"><span class="d-block d-lg-none"><i class="fa fa-search" aria-hidden="true"></i> Search</span><span class="d-none d-lg-block"><i class="fa fa-search" aria-hidden="true"></i></span></a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search"><i class="fa fa-search fa-fw text-muted pl-2" aria-hidden="true"></i></a>
          <input class="search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q" autocomplete="off">
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">
          {% if request.user.is_superuser %}
              <li class="nav-item form-inline">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'home:create' 1 %}">ایجاد</a>
              </li>
          {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="btn text-light" href="{% url 'accounts:user_logout' %}"> خروج </a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'accounts:user_register' %}"> ثبت نام </a>
              </li>
              <li class="nav-item">
                <a class="btn text-light" href="{% url 'accounts:user_login' %}"> ورود </a>
              </li>
          {% endif %}

      </ul>


    </div>

  </div>



</nav>

templates/inc/navbar3.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column" style="background-color: white;">
  <div class="container flex-row">

    <a class="navbar-brand" href="{% url 'home:home' %}" style="padding:2px">
      <img src="/static/media/turtle.gif" height="70" class="d-inline-block align-top" alt="اموزش پایتون">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">
        {% include 'inc/menu.html' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'start_here' %}" style="color:black"> شروع </a>
        </li>
      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/search" title="Search"><span class="d-block d-lg-none"><i class="fa fa-search" aria-hidden="true"></i> Search</span><span class="d-none d-lg-block"><i class="fa fa-search" aria-hidden="true"></i></span></a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search"><i class="fa fa-search fa-fw text-muted pl-2" aria-hidden="true"></i></a>
          <input class="search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;color:black" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q" autocomplete="off">
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">
          {% if request.user.is_superuser %}
              <li class="nav-item form-inline">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'home:create' 1 %}">ایجاد</a>
              </li>
          {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="btn" href="{% url 'accounts:user_logout' %}"> خروج </a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_register' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> ثبت نام </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> ورود </a>
              </li>
          {% endif %}

      </ul>


    </div>

  </div>



</nav>

templates/inc/navbar4.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column" style="background-color: rgb(14,151,195);">
  <div class="container flex-row">

    <a class="navbar-brand" href="{% url 'home:home' %}" style="padding:2px">
      <img src="/static/media/w1.jfif" height="70" class="d-inline-block align-top" alt="اموزش پایتون">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">
        {% include 'inc/menu.html' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'start_here' %}"
             style="color:black;border: 1px solid skyblue;border-radius: 11px;"> شروع </a>
        </li>
      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/search" title="Search"><span class="d-block d-lg-none"><i class="fa fa-search" aria-hidden="true"></i> Search</span><span class="d-none d-lg-block"><i class="fa fa-search" aria-hidden="true"></i></span></a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search"><i class="fa fa-search fa-fw text-muted pl-2" aria-hidden="true"></i></a>
          <input class="search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q" autocomplete="off">
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">
          {% if request.user.is_superuser %}
              <li class="nav-item form-inline">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'home:create' 1 %}">ایجاد</a>
              </li>
          {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> خروج </a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_register' %}"
                   style="color:white;border-radius: 11px;"> ثبت نام </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> ورود </a>
              </li>
          {% endif %}

      </ul>


    </div>

  </div>



</nav>

templates/inc/navbar5.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column" style="background-color: rgb(14,151,195);">
  <div class="container flex-row">

    <a class="navbar-brand" href="{% url 'home:home' %}" style="padding:2px">
      <img src="/static/media/w1.jfif" height="70" class="d-inline-block align-top" alt="اموزش پایتون">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">
        {% include 'inc/menu.html' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'start_here' %}"
             style="color:black;border: 1px solid skyblue;border-radius: 11px;"> شروع </a>
        </li>
      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/search" title="Search"><span class="d-block d-lg-none"><i class="fa fa-search" aria-hidden="true"></i> Search</span><span class="d-none d-lg-block"><i class="fa fa-search" aria-hidden="true"></i></span></a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search"><i class="fa fa-search fa-fw text-muted pl-2" aria-hidden="true"></i></a>
          <input class="search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q" autocomplete="off">
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">
          {% if request.user.is_superuser %}
              <li class="nav-item form-inline">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'home:create' 1 %}">ایجاد</a>
              </li>
          {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> خروج </a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_register' %}"
                   style="color:white;border-radius: 11px;"> ثبت نام </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> ورود </a>
              </li>
          {% endif %}

      </ul>


    </div>

  </div>



</nav>

templates/inc/navbar6.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column" style="background-color: rgb(14,151,195);">
  <div class="container flex-row">

    <a class="navbar-brand" href="{% url 'home:home' %}" style="padding:2px">
      <img src="/static/media/w1.jfif" height="70" class="d-inline-block align-top" alt="اموزش پایتون">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">
        {% include 'inc/menu.html' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'start_here' %}"
             style="color:black;border: 1px solid skyblue;border-radius: 11px;"> شروع </a>
        </li>
      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/search" title="Search"><span class="d-block d-lg-none"><i class="fa fa-search" aria-hidden="true"></i> Search</span><span class="d-none d-lg-block"><i class="fa fa-search" aria-hidden="true"></i></span></a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search"><i class="fa fa-search fa-fw text-muted pl-2" aria-hidden="true"></i></a>
          <input class="search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;" maxlength=50 type="search" placeholder="Search" aria-label="Search" name="q" autocomplete="off">
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">
          {% if request.user.is_superuser %}
              <li class="nav-item form-inline">
                <a class="ml-2 ml-lg-0 btn btn-sm btn-primary px-3" href="{% url 'home:create' 1 %}">ایجاد</a>
              </li>
          {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> خروج </a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_register' %}"
                   style="color:white;border-radius: 11px;"> ثبت نام </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}"
                   style="color:black;border: 1px solid skyblue;border-radius: 11px;"> ورود </a>
              </li>
          {% endif %}

      </ul>


    </div>

  </div>



</nav>